export const IPC = {
  getState: 'desktop:get-state',
  getConversation: 'desktop:get-conversation',
  getWebuiStatus: 'desktop:get-webui-status',
  openProject: 'desktop:open-project',
  registerProject: 'desktop:register-project',
  unregisterProject: 'desktop:unregister-project',
  openProjectSession: 'desktop:open-project-session',
  activateRuntime: 'desktop:activate-runtime',
  closeRuntime: 'desktop:close-runtime',
  navigateWebui: 'desktop:navigate-webui',
  reloadWebui: 'desktop:reload-webui',
  setShellSidebarCollapsed: 'desktop:set-shell-sidebar-collapsed',
  openSettings: 'desktop:open-settings',
  sendMessage: 'desktop:send-message',
  abortRuntime: 'desktop:abort-runtime',
  openRuntimeInBrowser: 'desktop:open-runtime-in-browser',
  revealRuntimeRoot: 'desktop:reveal-runtime-root',
  stateChanged: 'desktop:state-changed',
  conversationChanged: 'desktop:conversation-changed',
  webuiStatusChanged: 'desktop:webui-status-changed',
  webuiReadyChanged: 'desktop:webui-ready-changed',
  webuiPrefsChanged: 'desktop:webui-prefs-changed',
  webuiCommandAck: 'desktop:webui-command-ack',
  webuiCommand: 'desktop:webui-command',
  shellSidebarCollapsedChanged: 'desktop:shell-sidebar-collapsed-changed',
} as const;
